language: go

go:
  - "1.12"

# safelist - Build only for dev, master and tags
branches:
  only:
  - dev
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
  - docker

before_script:
  - go mod verify

script:
  - make container-image

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push softplan/tenkai-api:$TRAVIS_BRANCH;
    fi
