language: go

go:
  - "1.12"

# safelist - Build only for dev, master and tags
branches:
  only:
  - dev
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
  - docker

stages:
  - build
  - test
  - publish

jobs:
  include:
    - stage: build
      script:
        - make build
    - stage: test
      script:
        - make test
      stage: publish
        - make container-image
        - make tag-image
        - make publish
