language: go

go:
  - "1.12"

services:
  - docker

before_script:
  - go mod verify

script:
  - make container-image

after_success:
  - if [[ "$TRAVIS_BRANCH" == "develop" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker push softplan/tenkai-api:latest;
    fi
