language: go

go:
  - "1.12"

# safelist - Build only for dev, master and tags
branches:
  only:
  - dev
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

services:
  - docker

before_script:
  - go mod verify

script:
  - make build
  - make container-image
  - make tag-image
  - make publish
