server:
  port: 8080

app:
  dbms:
   uri: "host=172.21.25.22 port=5432 user=postgres dbname=tenkai sslmode=disable password=docker"

#app:
#  dbms:
#    uri: "host=172.21.25.22 port=5432 user=postgres dbname=tenkai-dev sslmode=disable password=docker"

