name: Tenkai-API CI

on: [push, pull_request]



jobs:
  build:
    runs-on: ubuntu-18.04
    env: 
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      
      - name: Install dependencies
        run: go get -u golang.org/x/lint/golint

      - name: Source Check
        run: |
          srccheck/verify-gofmt.sh
          srccheck/verify-govet.sh
          srccheck/verify-golint.sh

