name: Tenkai-API CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    env: 
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # - name: Lint
      #   run: make lint
      
      # - name: Test
      #   run: make test

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v1.6
      #   with:
      #     projectBaseDir: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build
        run: make build
      
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}/build/tenkai-api
  dockerize:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: 
      - name: Dockerize
        run: |
          make container-image
          make tag-image
            