name: Tenkai-API CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Before Script
        run: |
          srccheck/verify-gofmt.sh
          srccheck/verify-govet.sh
          srccheck/verify-golint.sh

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6

      - name: Dockerize
        run: |
          make container-image

          
