name: Tenkai-API CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    env: 
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # - name: Source Check
      #   run: |
      #     srccheck/verify-gofmt.sh
      #     srccheck/verify-govet.sh
      #     srccheck/verify-golint.sh
      
      # - name: Test
      #   run: make test

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v1.6
      #   with:
      #     projectBaseDir: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Build
        run: make build
      
      - name: Archive build artifact
        run: ls